### ISSUE TITLE
Name unifiers in config file to be referenced from command line

### ISSUE THREAD

**Issue by bengsparks** [pvs-hd-tea/PyTypes#100]
```toml
[pytypes]
project = "PyTypes"

[[restrictive_subtype]]
kind = "subtype"
venv_path = "./.venv"
only_replace_if_base_was_traced = true

[[relaxed_subtype]]
kind = "subtype"
venv_path = "./.venv"
only_replace_if_base_was_traced = false

[[deduplicate]]
kind = "dedup"
```

then on the typegen-cli:

```bash
python main.py -p $PROJ_PATH --unifiers deduplicate,relaxed_subtype
```

**Comment by bengsparks** [comment]
Current syntax:
```toml
[pytypes]
project = "PyTypes"

stdlib_path = "/usr/lib/python3.10"
proj_path = "/home/benji/Documents/Uni/heidelberg/04/pytype/repo"
venv_path = "/home/benji/.cache/pypoetry/virtualenvs/pytypes-xvtnrWJT-py3.10"

[[unifier]]
name = "remove_dups"
kind = "dedup"

[[unifier]]
name = "ignore_test"
kind = "drop_test"
test_name_pat = "test_"

[[unifier]]
name = "drop_implicit_2"
kind = "drop_mult_var"

[[unifier]]
name = "drop_explicit_5"
kind = "drop_mult_var"
min_amount_types_to_drop = 5

[[unifier]]
name = "replace_subtypes_relaxed"
kind = "repl_subty"

[[unifier]]
name = "replace_subtypes_strict"
kind = "repl_subty"
only_replace_if_base_was_traced = true
```


`python main.py -p $PROJ_PATH --unifier deduplicate --unifier relaxed_subtype`
